CREATE DATABASE  IF NOT EXISTS `monsteruniversity` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `monsteruniversity`;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `peemp_empleado`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `peemp_empleado` (
  `EMP_ID` int(11) NOT NULL,
  `CAR_ID` int(11) NOT NULL,
  `SEX_ID` int(11) NOT NULL,
  `EST_ID` int(11) NOT NULL,
  `EMP_CEDULA` int(11) DEFAULT NULL,
  `EMP_NOMBRE` varchar(100) DEFAULT NULL,
  `EMP_TELEFONO` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`EMP_ID`),
  KEY `FK_EMPLEADO_CARGO` (`CAR_ID`),
  KEY `FK_EMPLEADO_ESTADO_CIVIL` (`EST_ID`),
  KEY `FK_EMPLEADO_SEXO` (`SEX_ID`),
  CONSTRAINT `FK_EMPLEADO_CARGO` FOREIGN KEY (`CAR_ID`) REFERENCES `pecar_cargo` (`CAR_ID`),
  CONSTRAINT `FK_EMPLEADO_ESTADO_CIVIL` FOREIGN KEY (`EST_ID`) REFERENCES `peest_estciv` (`EST_ID`),
  CONSTRAINT `FK_EMPLEADO_SEXO` FOREIGN KEY (`SEX_ID`) REFERENCES `pesex_sexo` (`SEX_ID`)
);
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `peemp_empleado` (`EMP_ID`, `CAR_ID`, `SEX_ID`, `EST_ID`, `EMP_CEDULA`, `EMP_NOMBRE`, `EMP_TELEFONO`) VALUES (1,1,2,1,1314344985,'Febe','098518071');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

