CREATE DATABASE  IF NOT EXISTS `monsteruniversity` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `monsteruniversity`;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `aeite_itesal`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `aeite_itesal` (
  `SAL_NUMERO` int(11) NOT NULL,
  `BIEN_ID` int(11) NOT NULL,
  `EMP_ID` int(11) NOT NULL,
  `ITESA_CANTIDADENTREGADA` int(11) DEFAULT NULL,
  PRIMARY KEY (`SAL_NUMERO`,`BIEN_ID`,`EMP_ID`),
  KEY `FK_BIENES_ITEM_SALIDA` (`BIEN_ID`),
  KEY `FK_ITEM_SALIDA_EMPLEADO` (`EMP_ID`),
  CONSTRAINT `FK_BIENES_ITEM_SALIDA` FOREIGN KEY (`BIEN_ID`) REFERENCES `mebie_bienes` (`BIEN_ID`),
  CONSTRAINT `FK_ITEM_SALIDA_EMPLEADO` FOREIGN KEY (`EMP_ID`) REFERENCES `peemp_empleado` (`EMP_ID`),
  CONSTRAINT `FK_SALIDA_ALMACEN_ITEM_SALIDA` FOREIGN KEY (`SAL_NUMERO`) REFERENCES `aesal_salalm` (`SAL_NUMERO`)
);
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `aeite_itesal` (`SAL_NUMERO`, `BIEN_ID`, `EMP_ID`, `ITESA_CANTIDADENTREGADA`) VALUES (1,1,1,10);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

