CREATE DATABASE  IF NOT EXISTS `monsteruniversity` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `monsteruniversity`;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `ceite_itesol`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ceite_itesol` (
  `SOL_NUMERO` int(11) NOT NULL,
  `BIEN_ID` int(11) NOT NULL,
  `ITES_CANTIDADSOLICITADA` int(11) DEFAULT NULL,
  `ITES_CANTIDADDESPACHADA` int(11) DEFAULT NULL,
  `ITES_VALORTOTAL` float DEFAULT NULL,
  PRIMARY KEY (`SOL_NUMERO`,`BIEN_ID`),
  KEY `FK_BIENES_ITEM_SOLICITUD` (`BIEN_ID`),
  CONSTRAINT `FK_BIENES_ITEM_SOLICITUD` FOREIGN KEY (`BIEN_ID`) REFERENCES `mebie_bienes` (`BIEN_ID`),
  CONSTRAINT `FK_SOLICITUD_COMPRA_ITEM_SOLICITUD` FOREIGN KEY (`SOL_NUMERO`) REFERENCES `cesol_solcom` (`SOL_NUMERO`)
);
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `ceite_itesol` (`SOL_NUMERO`, `BIEN_ID`, `ITES_CANTIDADSOLICITADA`, `ITES_CANTIDADDESPACHADA`, `ITES_VALORTOTAL`) VALUES (1,1,10,10,25000);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

