CREATE DATABASE  IF NOT EXISTS `monsteruniversity` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `monsteruniversity`;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `ceord_ordcon`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ceord_ordcon` (
  `ORD_NUMERO` int(11) NOT NULL,
  `PRO_ID` int(11) NOT NULL,
  `ORD_FECHAORDEN` date DEFAULT NULL,
  `ORD_FECHAENTREGA` date DEFAULT NULL,
  `ORD_MONTOTOTAL` float DEFAULT NULL,
  `ORD_APROVACIONDIRECTORFINANCIERO` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ORD_NUMERO`),
  KEY `FK_ORDEN_PROVEEDOR` (`PRO_ID`),
  CONSTRAINT `FK_ORDEN_PROVEEDOR` FOREIGN KEY (`PRO_ID`) REFERENCES `aepro_proveedor` (`PRO_ID`)
);
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `ceord_ordcon` (`ORD_NUMERO`, `PRO_ID`, `ORD_FECHAORDEN`, `ORD_FECHAENTREGA`, `ORD_MONTOTOTAL`, `ORD_APROVACIONDIRECTORFINANCIERO`) VALUES (1,1,'2012-12-12','2012-12-12',25000,1);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

