CREATE DATABASE  IF NOT EXISTS `monsteruniversity` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `monsteruniversity`;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `seven_ventan`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `seven_ventan` (
  `VEN_CODIGO` char(10) NOT NULL,
  `OPC_CODIGO` char(10) NOT NULL,
  `VEN_DESCRIPCION` varchar(100) NOT NULL,
  `VEN_MENSAJE` varchar(100) NOT NULL,
  PRIMARY KEY (`VEN_CODIGO`),
  KEY `FK_XR_XEOPC_XEVEN` (`OPC_CODIGO`),
  CONSTRAINT `FK_XR_XEOPC_XEVEN` FOREIGN KEY (`OPC_CODIGO`) REFERENCES `seopc_opcion` (`OPC_CODIGO`)
);
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `seven_ventan` (`VEN_CODIGO`, `OPC_CODIGO`, `VEN_DESCRIPCION`, `VEN_MENSAJE`) VALUES ('1','1','inicio','inicio');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

