CREATE DATABASE  IF NOT EXISTS `monsteruniversity` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `monsteruniversity`;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `seusu_usuari`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `seusu_usuari` (
  `EMP_ID` int(11) NOT NULL,
  `EST_CODIGO` char(10) NOT NULL,
  `USU_CONTRASENA` varchar(200) NOT NULL,
  `USU_PIEFIRMA` varchar(100) NOT NULL,
  `USU_FECHACREACION` datetime NOT NULL,
  `USU_FECHAULTIMOCAMBIO` datetime NOT NULL,
  PRIMARY KEY (`EMP_ID`),
  KEY `FK_XR_XEEST_XEUSU` (`EST_CODIGO`),
  CONSTRAINT `FK_XE_PEEMP_XEUSU` FOREIGN KEY (`EMP_ID`) REFERENCES `peemp_empleado` (`EMP_ID`),
  CONSTRAINT `FK_XR_XEEST_XEUSU` FOREIGN KEY (`EST_CODIGO`) REFERENCES `seest_estado` (`EST_CODIGO`)
);
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `seusu_usuari` (`EMP_ID`, `EST_CODIGO`, `USU_CONTRASENA`, `USU_PIEFIRMA`, `USU_FECHACREACION`, `USU_FECHAULTIMOCAMBIO`) VALUES (1,'1','1212','firma','2012-12-12 00:00:00','2012-12-12 00:00:00');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

