CREATE DATABASE  IF NOT EXISTS `monsteruniversity` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `monsteruniversity`;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `seusu_usaper`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `seusu_usaper` (
  `EMP_ID` int(11) NOT NULL,
  `PER_CODIGO` char(10) NOT NULL,
  `USUPER_FECHAASIGNACION` date NOT NULL,
  `USUPER_FECHACAMBIO` date NOT NULL,
  PRIMARY KEY (`EMP_ID`,`PER_CODIGO`),
  KEY `FK_SEUSU_USAPER` (`PER_CODIGO`),
  CONSTRAINT `FK_SEUSU_USAPER` FOREIGN KEY (`PER_CODIGO`) REFERENCES `seper_perfil` (`PER_CODIGO`),
  CONSTRAINT `FK_SEUSU_USAPER2` FOREIGN KEY (`EMP_ID`) REFERENCES `seusu_usuari` (`EMP_ID`)
);
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `seusu_usaper` (`EMP_ID`, `PER_CODIGO`, `USUPER_FECHAASIGNACION`, `USUPER_FECHACAMBIO`) VALUES (1,'1','2012-12-12','2012-12-12');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

