CREATE DATABASE  IF NOT EXISTS `monsteruniversity` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `monsteruniversity`;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `cesol_solcom`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cesol_solcom` (
  `SOL_NUMERO` int(11) NOT NULL,
  `EMP_ID` int(11) NOT NULL,
  `ARE_ID` int(11) NOT NULL,
  `RUB_CODIGO` int(11) NOT NULL,
  `SOL_FECHA` date DEFAULT NULL,
  `SOL_APROBACIONDIRECTORFINANCIERO` tinyint(1) DEFAULT NULL,
  `SOL_APROBACIONJEFEAREA` tinyint(1) DEFAULT NULL,
  `SOL_TOTAL` float DEFAULT NULL,
  PRIMARY KEY (`SOL_NUMERO`),
  KEY `FK_SOLICITUD_COMPRA_AREA` (`ARE_ID`),
  KEY `FK_SOLICITUD_COMPRA_EMPLEADO` (`EMP_ID`),
  KEY `FK_SOLICITUD_COMPRA_RUBRO_PRESUPUESTARIO` (`RUB_CODIGO`),
  CONSTRAINT `FK_SOLICITUD_COMPRA_AREA` FOREIGN KEY (`ARE_ID`) REFERENCES `peare_area` (`ARE_ID`),
  CONSTRAINT `FK_SOLICITUD_COMPRA_EMPLEADO` FOREIGN KEY (`EMP_ID`) REFERENCES `peemp_empleado` (`EMP_ID`),
  CONSTRAINT `FK_SOLICITUD_COMPRA_RUBRO_PRESUPUESTARIO` FOREIGN KEY (`RUB_CODIGO`) REFERENCES `cerub_rubpre` (`RUB_CODIGO`)
);
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `cesol_solcom` (`SOL_NUMERO`, `EMP_ID`, `ARE_ID`, `RUB_CODIGO`, `SOL_FECHA`, `SOL_APROBACIONDIRECTORFINANCIERO`, `SOL_APROBACIONJEFEAREA`, `SOL_TOTAL`) VALUES (1,1,1,1,'2012-12-12',1,1,25000);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

